[package]
name = "unwind"
version = "0.1.0"
authors = ["Gary Guo <gary@garyguo.net>"]
edition = "2018"

[dependencies]
gimli = { version = "0.25.0", default-features = false, features = ["read"] }
libc = { version = "0.2", optional = true }
spin = { version = "0.9", default-features = false, features = ["mutex", "spin_mutex"] }

[features]
alloc = []
fde-phdr = ["libc"]
fde-registry = ["alloc"]
default = ["fde-phdr"]

[profile.release]
debug = true
