[package]
name = "unwind"
version = "0.1.0"
authors = ["Gary Guo <gary@garyguo.net>"]
edition = "2018"

[dependencies]
gimli = { version = "0.25.0", default-features = false, features = ["read"] }
libc = "0.2"
once_cell = { version = "1.8", optional = true }
spin = { version = "0.9", default-features = false, features = ["lazy", "mutex", "spin_mutex"] }

[features]
std = ["once_cell"]

[profile.release]
debug = true
