[package]
name = "unwind_dyn"
version = "0.1.0"
authors = ["Gary Guo <gary@garyguo.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
unwind = { path = "../", features = ["system-alloc"] }
libc = "0.2"
